### ISSUE TITLE
BARCODE_DECODERS[options.barcode] is not a function

### ISSUE THREAD

**Issue by ezos86** [mubaidr/Javascript-Barcode-Reader#102]
This comes up when trying to run.

**Comment by mubaidr** [comment]
What did you pass in `options.barcode`, please?

I see there could be naming confusion, I will fix it. https://github.com/mubaidr/Javascript-Barcode-Reader#available-decoders

**Comment by mubaidr** [comment]
Some updated pushed, please try and let me know: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/2177e6555bd13b7d64ceceb0fa927ad4ee1813f4

**Comment by mubaidr** [comment]
Closing until update.
