### ISSUE TITLE
DOMException: "Index or size is negative or greater than the allowed amount"

### ISSUE THREAD

**Issue by sistemasnegros** [mubaidr/Javascript-Barcode-Reader#109]
pass img document.getElementById('image');  

DOMException: "Index or size is negative or greater than the allowed amount"

**Comment by mubaidr** [comment]
Will look into this issue.

**Comment by mubaidr** [comment]
I could not find the issue. Can you please see this sample code from demo and try again in your code? 

https://github.com/mubaidr/Javascript-Barcode-Reader/blob/master/docs/demo.js#L9

Otherwise, please provide some example code.

**Comment by sistemasnegros** [comment]
solved, its works
