### ISSUE TITLE
package.json typing 文件写错

### ISSUE THREAD

**Issue by hxdyj** [mubaidr/Javascript-Barcode-Reader#1125]
**Describe the bug**
package.json typing 文件写错

**To Reproduce**
  "typings": "dist/types/javascript-barcode-reader.d.ts",

**Expected behavior**
  "typings": "dist/types/src/index.d.ts",

**Comment by mubaidr** [comment]
Confirmed. Are you willing to create a pull request for this fix?

**Comment by hxdyj** [comment]
Thank you for your reply. I am already fix by `patch-package`.

**Comment by mubaidr** [comment]
No. Problem. I will update the repo.

**Comment by mubaidr** [comment]
https://github.com/mubaidr/Javascript-Barcode-Reader/commit/0a121ca1066c9aede472535de25bfac10ad27bdf
