### ISSUE TITLE
Interleaved 2 of 5 returns nothing

### ISSUE THREAD

**Issue by danielreyes61** [mubaidr/Javascript-Barcode-Reader#1136]
**Describe the bug**
Interleaved 2 of 5 does not err out but does return a blank line to console. Other barcode test was EAN-13 and worked as expected.

**To Reproduce**
Steps to reproduce the behavior: Scan attached Interleaved 2 of 5 barcode
![barcode_bug](https://user-images.githubusercontent.com/10054066/124065223-2b2f6380-d9eb-11eb-9997-c0e72dadc912.png)

**Expected behavior**
Return integer 1234567895

**Comment by mubaidr** [comment]
It works as expected if you specify following options: 

```
barcode: "code-2of5",
barcodeType: "interleaved"
```

working example: https://codesandbox.io/s/javascript-barcode-reader-forked-s3led
