### ISSUE TITLE
UPC-A barcode support

### ISSUE THREAD

**Issue by danielreyes61** [mubaidr/Javascript-Barcode-Reader#1137]
**Is your feature request related to a problem? Please describe.**
Added support for library but need UPC-A barcode scanning ability's.
**Describe the solution you'd like**
Scan UPC-A barcode and return decoded barcode information.

**Describe alternatives you've considered**
Considered using QuaggaJS

**Comment by mubaidr** [comment]
I think EAN and UPC-A are exactly the same graphically. Can you please trying EAN as barcode option and scan UPC code?

**Comment by danielreyes61** [comment]
EAN is working at reading UPC-A, thank you!
