### ISSUE TITLE
Implement QR Code

### ISSUE THREAD

**Issue by mhosman** [mubaidr/Javascript-Barcode-Reader#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mubaidr** [comment]
Actually I don't know how QR codes work. I will try to learn that and see if i can implement it. But first I would like to test this: 
https://github.com/mubaidr/Javascript-Barcode-Reader/issues/139
