### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mgonzo10** [mubaidr/Javascript-Barcode-Reader#212]
Hi,
I am trying to run this on Node.js and keep running into this error: "Uncaught ReferenceError: regeneratorRuntime is not defined
    at a (index.js:24)
    at r (index.js:24)".
Is this issue with installation or something else?

**Comment by mgonzo10** [comment]
Great, thank you for the quick response!

**Comment by mubaidr** [comment]
It seems that you are using browser build on nodejs, can you please try this code and let me know? 
```js
const javascriptBarcodeReader = require('javascript-barcode-reader')
```

**Comment by mgonzo10** [comment]
I am now receiving a different error and due to my lack of understanding of how this barcode reader works, I am not sure if it is my implementation or not.  The error I am receiving now is: "Uncaught TypeError: (intermediate value).then is not a function".  What is the promise in this instance?

**Comment by mgonzo10** [comment]
Also, I noticed that the demo is broken

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/3824bf719598379b6021748006941e86d2491742
