### ISSUE TITLE
The problem used in vue

### ISSUE THREAD

**Issue by zdd2018** [mubaidr/Javascript-Barcode-Reader#247]
It will report this error when used in vue.
```
TypeError: javascriptBarcodeReader is not a function
```
It is useless to use the following two methods of reference
```
const javascriptBarcodeReader = require('javascript-barcode-reader')

```
```
import   javascriptBarcodeReader from 'javascript-barcode-reader'
```

**Comment by mubaidr** [comment]
Can you please share the code portion where you are using this module?

**Comment by mubaidr** [comment]
Should be fixed in: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/29650806f0f77be8f289e3f17ed7cae2e6bb63d4

**Comment by zdd2018** [comment]
> Can you please share the code portion where you are using this module?

I just use  npm to install it，then through following method call it.
```
                var input = document.querySelector(" input[type=file]");
                const img = URL.createObjectURL(input.files[0])

                const javascriptBarcodeReader = require('javascript-barcode-reader')
                javascriptBarcodeReader(
                    img /* Image file Path || {data: pixelArray, width, height} || HTML5 Canvas ImageData */,
                    {
                        barcode: 'code-2of5',
                        type: 'industrial', //optional type
                    }
                )
                    .then(code => {
                        console.log(code)
                    })
                    .catch(err => {
                        console.log(err)
                    })
```

**Comment by mubaidr** [comment]
Please try to use newer version, it should load as expected. Though in your code you need to create an `Image` object and then assign source (from URL.createObjectURL(input.files[0])) to it.

**Comment by zdd2018** [comment]
> Please try to use newer version, it should load as expected. Though in your code you need to create an `Image` object and then assign source (from URL.createObjectURL(input.files[0])) to it.

Thank you,but there are still some barcodes that cannot be recognized.
Like this.
![boxcode](https://user-images.githubusercontent.com/43198565/63322192-61aee880-c355-11e9-9749-63b338f99823.png)

**Comment by mubaidr** [comment]
I will look into this matter, in the mean time please provide more info (barcode type) here: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/250
