### ISSUE TITLE
Pre-process images to improve precision

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/Javascript-Barcode-Reader#250]
**Describe the bug**
there are still some barcodes that cannot be recognized.

**To Reproduce**
![63322192-61aee880-c355-11e9-9749-63b338f99823](https://user-images.githubusercontent.com/2222702/63324136-523f8900-c2dc-11e9-958f-45121f51862b.png)

@zdd2018

**Comment by zdd2018** [comment]
The detailed information：
```
{
  "BarcodeFormat": "BF_CODE_128",
  "BarcodeFormatString": "CODE_128",
  "BarcodeText": "L89HE1806005080432",
  "BarcodeBytes": "TDg5SEUxODA2MDA1MDgwNDMy",
  "LocalizationResult": {
    "TerminatePhase": "TP_BARCODE_RECOGNIZED",
    "BarcodeFormat": "BF_ONED",
    "BarcodeFormatString": "OneD",
    "Angle": 0,
    "ResultPoints": [
      "2, 6",
      "95, 6",
      "95, 73",
      "2, 73"
    ],
    "ModuleSize": 4,
    "PageNumber": 0,
    "RegionName": "",
    "DocumentName": null,
    "AccompanyingTextBytes": null
  },
  "_Confidence": 73
}
```
 I test it on [https://demo.dynamsoft.com/DBR/BarcodeReaderDemo.aspx](https://demo.dynamsoft.com/DBR/BarcodeReaderDemo.aspx)

**Comment by mubaidr** [comment]
For information please: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/272

**Comment by mubaidr** [comment]
This is due to image degradation issue. I will be adding feature to pre-process image to enhance its precision.

**Comment by mubaidr** [comment]
Applying threshold to the image improves the result a lot. e.g.:
![Capture](https://user-images.githubusercontent.com/2222702/64925392-51c9dd80-d809-11e9-8933-f1d6db51c99c.PNG)

I am still working trying to get it 100% right. 

Probably adding noise filter/removal will help further.

**Comment by joseph-animasds** [comment]
@mubaidr - how is this coming along? I find myself converting a pdf to a very large image ( too big to open in windows Paint) and cropping it and still sometimes a character is not readable

**Comment by mubaidr** [comment]
I have tried at-least two image threshold (OTSU, Normalized Histogram Threshold) algorithms but no success. Currently I am finishing with the third one. This will fix the: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/250#issuecomment-531584671 but further improvements will be required to fix/enhance this: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/277

**Comment by joseph-animasds** [comment]
not sure why this one isnt reading:
![croppedImage](https://user-images.githubusercontent.com/45604274/65794755-0f1bd580-e126-11e9-8918-24618efdc76c.png)

**Comment by mubaidr** [comment]
This issue should be solved in by https://github.com/mubaidr/Javascript-Barcode-Reader/commit/ec4535f49c211944e8115cbe4a43d2b7b21afc41
