### ISSUE TITLE
code-128

### ISSUE THREAD

**Issue by joseph-animasds** [mubaidr/Javascript-Barcode-Reader#272]
**Describe the bug**
When reading a png image of only the barcode and using the code-128 decoder, An error is thrown "Failed to extract barcode"
Here is my code:
![image](https://user-images.githubusercontent.com/45604274/64734106-38d8c980-d4a3-11e9-8232-8141c7bda9ec.png)

![image](https://user-images.githubusercontent.com/45604274/64734035-1c3c9180-d4a3-11e9-97fa-7cd891a9cdcd.png)

![image](https://user-images.githubusercontent.com/45604274/64734002-0dee7580-d4a3-11e9-9d6f-d296fdbb16f9.png)
Here is the error:
![image](https://user-images.githubusercontent.com/45604274/64733959-f9aa7880-d4a2-11e9-9d0e-78283ac11aa0.png)

**Desktop (please complete the following information):**
 - Node version 10.14.1
 - Library version "^0.4.18"

**Comment by mubaidr** [comment]
Please share the image you are trying to use.

**Comment by joseph-animasds** [comment]
It is attached. This came from a pdf that I converted to image and then
cropped it. Maybe the conversion to image is corrupting it. But that seems
odd.

**Comment by mubaidr** [comment]
I am sorry but I still cannot see the barcode image. :(

**Comment by joseph-animasds** [comment]
It is attached to the email. Let me know if you still can't see it

**Comment by mubaidr** [comment]
**Attachment to email might not work, please attach image here.**

**Comment by mubaidr** [comment]
For the above image: 
Expected: "33c64780-a9c0-e92a-820c-fae7011c11e2"
Received: "33ETX4780-SOH9ETX0-ENQ2SOH80ETX-SOHENQ70111ENQ2"

Looks like this package is not decoding code-128 properly. I am working on it.

**Comment by mubaidr** [comment]
Interesting: So if I try to use this online service to generate image for same code, it is extracted by this package as expected. 

https://barcode.tec-it.com/en/?data=33c64780-a9c0-e92a-820c-fae7011c11e2
![33c64780-a9c0-e92a-820c-fae7011c11e2](https://user-images.githubusercontent.com/2222702/64873134-e42f7d00-d661-11e9-832f-2669779a83d5.gif)

**Comment by joseph-animasds** [comment]
@mubaidr - is it because of the type of image. In the generated image it is a gif. but the one i supplied is a png

**Comment by joseph-animasds** [comment]
@mubaidr - the image is a little blurry when I zoom in. could that be why?

**Comment by mubaidr** [comment]
Actually i have compared two images using an online image difference tool. Looks like there are atleast two portions in your provided image which are different than the above generated Image (uploaded by me). So i think it is related to some encoding configuration.

**Comment by joseph-animasds** [comment]
@mubaidr - Are you working on a fix then?

**Comment by mubaidr** [comment]
Yes, I am working on it. Stay tuned!

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/7536e9882c51717b20d96fe38364b3135034729b

You may still note that some characters cannot be identified, this is due to image degradation issue. I will be adding feature to pre-process image to enhance its precision. You can follow it up here: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/250
