### ISSUE TITLE
Some characters are incorrect

### ISSUE THREAD

**Issue by joseph-animasds** [mubaidr/Javascript-Barcode-Reader#277]
compare real results with output in this image as there seems to be questions marks when there should be other numbers:

![image](https://user-images.githubusercontent.com/45604274/64912148-66fb1b00-d6e8-11e9-9827-d66e390720a4.png)

**Comment by joseph-animasds** [comment]
using this image:
![croppedImage](https://user-images.githubusercontent.com/45604274/64912167-9b6ed700-d6e8-11e9-8a0f-12724064e3d2.png)

**Comment by mubaidr** [comment]
https://github.com/mubaidr/Javascript-Barcode-Reader/issues/250#issuecomment-531584671

**Comment by mubaidr** [comment]
Result for: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/250#issuecomment-536058580

![65794755-0f1bd580-e126-11e9-8918-24618efdc76c](https://user-images.githubusercontent.com/2222702/65871482-5d51f400-e333-11e9-9227-a27bdc094fbd.png)

![65794755-0f1bd580-e126-11e9-8918-24618efdc76c-result](https://user-images.githubusercontent.com/2222702/65871527-735fb480-e333-11e9-963f-a97ee6cb4cd8.png)

**Comment by joseph-animasds** [comment]
thanks. let me know when you have that!

**Comment by mubaidr** [comment]
This is fixed in latest version: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/4094c6533a4e6ebf47ded616b0db230126d9c246
