### ISSUE TITLE
Error: Crc error - -1346...

### ISSUE THREAD

**Issue by joseph-animasds** [mubaidr/Javascript-Barcode-Reader#288]
I ran the barcode in a loop and it read 2 out of three barcodes. The very first barcode it attempted to read gave me this error:
![image](https://user-images.githubusercontent.com/45604274/66083877-8688a500-e52a-11e9-9178-105a4f35146c.png)

**Comment by mubaidr** [comment]
Share the barcode image pls.

**Comment by mubaidr** [comment]
BTW this error is being originated from `pngjs` not from this module.

**Comment by joseph-animasds** [comment]
I'll close, seems like a bug in my code, not yours.
