### ISSUE TITLE
Some Barcodes aren't read correctly

### ISSUE THREAD

**Issue by joseph-animasds** [mubaidr/Javascript-Barcode-Reader#296]
![K1JPGUVF@DGYAMJ2 glagsec111](https://user-images.githubusercontent.com/45604274/66517883-31581080-eaa1-11e9-9a37-b9b21b9203f5.png)

when reading this image above with your older version, 4.20, I get some characters coming back as different letters than they should be 9f31b336-647c-f8d1-5?10-?Shift Ai4dc7fa0
, when using newest version 5.4, it is unable to extract at all with the Error: Failed to extract barcode !
What the code actually should be is - 9f31b336-647c-f8d1-5910-987320dc7fa0

**Comment by DanielTurner** [comment]
![ean-13](https://user-images.githubusercontent.com/3478688/66622594-9ccde980-ec2b-11e9-9f5a-ba62cdd63b40.png)
This is returning as 1 on your demo site.

**Comment by mubaidr** [comment]
Looking into the issue, looks like latest update broke something. :(

**Comment by joseph-animasds** [comment]
@mubaidr - any update?

**Comment by mubaidr** [comment]
Tracked here: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/373
