### ISSUE TITLE
Please add versions & tag releases

### ISSUE THREAD

**Issue by DanielTurner** [mubaidr/Javascript-Barcode-Reader#298]
Please consider using versions to tag your releases so we can fallback to the old version using the cdn with the version number.

**Comment by mubaidr** [comment]
You can specify version whne using cdn:
```html
<script src="//unpkg.com/javascript-barcode-reader@0.4.2/dist/javascript-barcode-reader.min.js"></script>
```

I will try to add tags to newer releases.

**Comment by DanielTurner** [comment]
Thank you for this.
