### ISSUE TITLE
scan barcode from camera?

### ISSUE THREAD

**Issue by chovy** [mubaidr/Javascript-Barcode-Reader#355]
Can someone point me in the right direction for how to scan a barcode from the camera?

**Comment by mubaidr** [comment]
Although you can use this module to scan bar-code from webcam, but it not recommended. More info: 
https://github.com/mubaidr/Javascript-Barcode-Reader#known-issues

This library is written to written to satisfy 2 needs, simplicity to use and performance thus currently lacks some other features as to find bar-code in image or detect rotated bar-codes. 

But I do have plans to support these features, but right now I don't have enough time. :(

I would recommend trying out this library: https://github.com/serratus/quaggaJS
