### ISSUE TITLE
Javascript barcode reader is not a function

### ISSUE THREAD

**Issue by joseph-animasds** [mubaidr/Javascript-Barcode-Reader#392]
**Describe the bug**
I just implemented the newest version and I got the error 'TypeError: javascriptBarcodeReader is not a function' using this code:
![image](https://user-images.githubusercontent.com/45604274/75360698-6cea5000-5873-11ea-8fc6-150fed85215e.png)

**To Reproduce**
use this code:
![image](https://user-images.githubusercontent.com/45604274/75360718-72479a80-5873-11ea-92fb-d060317ad1a7.png)

**Expected behavior**
a code to be read
**Screenshots**

**Desktop (please complete the following information):**
 - Node Or Browser version [e.g. 10]
10.14.1
 - Library version [e.g. 22]
6.1
**Additional context**
![image](https://user-images.githubusercontent.com/45604274/75360806-90ad9600-5873-11ea-82b2-859f4de47c66.png)

**Comment by mubaidr** [comment]
Try 
```js
import { javascriptBarcodeReader } from 'javascript-barcode-reader'
// or
const { javascriptBarcodeReader } = require('javascript-barcode-reader')
```

Or update to latest version and then this will aslo work: 
```js
const javascriptBarcodeReader = require('javascript-barcode-reader')
```

**Comment by joseph-animasds** [comment]
> Try
> 
> ```js
> import { javascriptBarcodeReader } from 'javascript-barcode-reader'
> // or
> const { javascriptBarcodeReader } = require('javascript-barcode-reader')
> ```
> 
> in latest version, this should also work:
> 
> ```js
> const javascriptBarcodeReader = require('javascript-barcode-reader')
> ```

I am updated to the latest. Adding the curly braces around the constant worked. thanks
