### ISSUE TITLE
How can I pass the path of an image from nodejs?

### ISSUE THREAD

**Issue by YeisonVelez11** [mubaidr/Javascript-Barcode-Reader#40]
Excuse ignorance, your bookstore looks great. But since nodejs I am running:

node app.js

`
    // Node.js
    const javascriptBarcodeReader = require('javascript-barcode-reader')

    const code = javascriptBarcodeReader("baaaaar.PNG" /* ImageData */, {
    barcode: 'code-2of5',
    type: 'industrial', //standard/interleaved optional type
    })

`

and I get this error:

C:\xampp\htdocs\barcode3\node_modules\javascript-barcode-reader\src\index.js:29
    imageSource = document.getElementById(imageSource)
    ^

ReferenceError: document is not defined

I'm trying to read the bar code and I need to get the answer. It's possible?
thank you.

**Comment by mubaidr** [comment]
Progress: https://github.com/mubaidr/Javascript-Barcode-Reader/commit/4cf7685ea8b71ff6a3baee6c78d355b2194655fc

Initial support is implemented for file path or buffer support in Node.js, I will publish newer version to npm after some testing.

**Comment by YeisonVelez11** [comment]
many thanks! You are all a crack. I am very grateful to you. I enclose a barcode image in case you are interested in trying.



________________________________
De: Muhammad Ubaid Raza <notifications@github.com>
Enviado: jueves, 11 de octubre de 2018 1:52 p.m.
Para: mubaidr/Javascript-Barcode-Reader
Cc: YeisonVelez11; Author
Asunto: Re: [mubaidr/Javascript-Barcode-Reader] How can I pass the path of an image from nodejs? (#40)


Progress: 4cf7685<https://github.com/mubaidr/Javascript-Barcode-Reader/commit/4cf7685ea8b71ff6a3baee6c78d355b2194655fc>

Initial support is implemented for file path or buffer support in Node.js, I will publish newer version to npm after some testing.

**Comment by YeisonVelez11** [comment]
This would be great, because there are applications that from the back-end side only need to receive the path of the image and then execute their respective callback.

**Comment by nikhilkinkar** [comment]
I have to read barcode from uploaded images in node.js, so I am using [canvas](https://www.npmjs.com/package/canvas) for getting ImageData, but still I am getting output as _null_, no warning, no error. Can you suggest what might be getting wrong there.

**Comment by nikhilkinkar** [comment]
@mubaidr I think it is possibly canvas issue, not the javascript-barcode-reader issue, because I inspected the ImageData, Uint8ClampedArray included all 0.
passing on file path instead of ImageData is a great idea.

**Comment by YeisonVelez11** [comment]
@mubaidr  Yes, thank you very much. I can not wait to see how it works. the whole world will thank you. (I have not found anything that works for me for nodejs.)

**Comment by mubaidr** [comment]
V0.4 is published now with new promise api and node.js file read support.

**Comment by nikhilkinkar** [comment]
@mubaidr can we read multiple barcodes from single image in V0.4 ?

**Comment by YeisonVelez11** [comment]
thank you very much friend, sorry for the delay. You are a genious. unfortunately this solution does not work for me. this is the code I am using:


const javascriptBarcodeReader = require('javascript-barcode-reader')

//using promise
javascriptBarcodeReader(
    "bar.jpg",
  {
    barcode: 'code-2of5',
    type: 'industrial', //optional type
  }
).then(code => {
  console.log(code)
})

//using await
var code = await javascriptBarcodeReader(
    "bar.jpg",
  {
    barcode: 'code-2of5',
    type: 'industrial', //optional type
  }
)
console.log(code);



I'm using the attached image, I think it's "Code128". How can I do to recognize it? (the result is a string of numbers)
and another doubt and excuse my ignorance but with "await" I do not know how to perform a "console.log ()".
I hope you can help me please. Thank you and God bless you, greetings from Colombia.

**Comment by mubaidr** [comment]
Please check this example: https://runkit.com/mubaidr/5bc8248977b2580014643bec

You will use local file path when in Node.js

**Comment by YeisonVelez11** [comment]
usin this code:


var javascriptBarcodeReader = require("javascript-barcode-reader")

javascriptBarcodeReader(
'code128.png',
{
barcode: 'code-128',
}
).then(code => {
console.log(code)
})


I am getting:


"

(node:18256) UnhandledPromiseRejectionWarning: Error: Failed to extract barcode!
    at Promise (C:\xampp\htdocs\barcode7\node_modules\javascript-barcode-reader\src\index.js:118:19)
    at new Promise (<anonymous>)
    at barcodeDecoder (C:\xampp\htdocs\barcode7\node_modules\javascript-barcode-reader\src\index.js:33:10)
(node:18256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

________________________________
De: Yeison Velez <yeison_velez11@hotmail.com>
Enviado: jueves, 18 de octubre de 2018 8:24 a.m.
Para: mubaidr/Javascript-Barcode-Reader
Asunto: Re: [mubaidr/Javascript-Barcode-Reader] How can I pass the path of an image from nodejs? (#40)

Thank you for responding and your valuable help. I do not know what I'm doing wrong, I've tried with these images and I get this error.
I hope you can help me please
(please see "Captura.png", it contains my problem)
var javascriptBarcodeReader = require("javascript-barcode-reader")

const code = await javascriptBarcodeReader(
'code128.png',
{
barcode: 'code-128',
}
)

console.log(code)


________________________________
De: Muhammad Ubaid Raza <notifications@github.com>
Enviado: jueves, 18 de octubre de 2018 1:15 a.m.
Para: mubaidr/Javascript-Barcode-Reader
Cc: YeisonVelez11; Mention
Asunto: Re: [mubaidr/Javascript-Barcode-Reader] How can I pass the path of an image from nodejs? (#40)


Please check this example: https://runkit.com/mubaidr/5bc8248977b2580014643bec

You will use local file path when in Node.js

**Comment by mubaidr** [comment]
Can you please share the image?

**Comment by YeisonVelez11** [comment]
thanks crack!




________________________________
De: Muhammad Ubaid Raza <notifications@github.com>
Enviado: lunes, 22 de octubre de 2018 11:26 a.m.
Para: mubaidr/Javascript-Barcode-Reader
Cc: YeisonVelez11; Mention
Asunto: Re: [mubaidr/Javascript-Barcode-Reader] How can I pass the path of an image from nodejs? (#40)


Please provide the image you are using, so that i could test on it, and the i will be able to help you.

**Comment by YeisonVelez11** [comment]
Thanks crack!!

________________________________
De: Muhammad Ubaid Raza <notifications@github.com>
Enviado: lunes, 22 de octubre de 2018 11:26 a.m.
Para: mubaidr/Javascript-Barcode-Reader
Cc: YeisonVelez11; Mention
Asunto: Re: [mubaidr/Javascript-Barcode-Reader] How can I pass the path of an image from nodejs? (#40)


Please provide the image you are using, so that i could test on it, and the i will be able to help you.

**Comment by mubaidr** [comment]
There is no image attached in Github comments or emails, please attach an image here inside Github comments.
