### ISSUE TITLE
Invalid output for code-128

### ISSUE THREAD

**Issue by helia19s** [mubaidr/Javascript-Barcode-Reader#60]
I just tried your barcode scanner and in doesn't  output the correct code . 
![out1543866496818h](https://user-images.githubusercontent.com/24384645/49398127-b15f6c80-f752-11e8-8fc6-8626fe073e22.jpg)
 it should output  79619647103200000134407005 .
but in shows 7961964710320013440705. 
 that lacks multiple 0! 
type: code-128;

how can i fix it?

**Comment by mubaidr** [comment]
Confirmed!

I will look into this issue.

**Comment by mubaidr** [comment]
Fixed in v0.4.9 https://github.com/mubaidr/Javascript-Barcode-Reader/commit/e817a5740304b000b63e997ec687b6523e5d0c8a
