### ISSUE TITLE
Wrong output, EAN13

### ISSUE THREAD

**Issue by lucifer63** [mubaidr/Javascript-Barcode-Reader#72]
I just came across your [example page](https://mubaidr.js.org/Javascript-Barcode-Reader/), pressed _Scan_ under EAN13 image and noticed that output code 901234123457 is not the code that i see at the image.

Is it intentionally? Or is it the barcode fault?

**Comment by mubaidr** [comment]
It is i tentional. First digit is padding or check digit, but code-128 do have another bug: https://github.com/mubaidr/Javascript-Barcode-Reader/issues/60

**Comment by lucifer63** [comment]
Ok, i got it. I think only USA folks use 12 digits from EAN13 code, therefore be aware that many systems in many countries use the whole 13-digit code. Like Russian: here in Russia all the shops use 13-code digit and they don't care what first digit means in any other country. So they will not be able to use your barcode reader implementation.

**Comment by mubaidr** [comment]
I will look into this issue too. I don't have much time these days, but surely some day.
