### ISSUE TITLE
Scan image without barcode

### ISSUE THREAD

**Issue by Bajdzis** [mubaidr/Javascript-Barcode-Reader#82]
When I call your function with image and without barcode, I get promise resolve with error "Error: Failed to extract barcode!". In my opinion you should reject promise with this error.

```
barcodeReader(this.ctx.getImageData(0, 0, this.canvasElement.width, this.canvasElement.height), {
    barcode: 'ean-13'
})
    .then((code) => {
        console.log(code);
    })
    .catch((err) => {
        console.log(err);
    });
```

**Comment by mubaidr** [comment]
Confirmed. Will correct this behaviour ious soon.

**Comment by mubaidr** [comment]
https://github.com/mubaidr/Javascript-Barcode-Reader/commit/1af091e72ba94b39fb96a612f212454f9c9b6994
